### ISSUE TITLE
Removing .git

### ISSUE THREAD

**Issue by Cmdv** [deadlyhifi/wp-gate8#1]
When pulling down the repo would be great when installing to remove the .git folder so you can set your own up instead of being attached to the original .git

do you think this would be a good idea?

**Comment by deadlyhifi** [comment]
Will have to look into removing the git folder on first setup only. Otherwise it might delete your .git folder and that would be bad.

**Comment by Cmdv** [comment]
Would it be worth initialising a new empty git? I think most people downloading this dependency with want git included just maybe not the original master.
